version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_passeiosturisticos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  turismo-java:
    build:
      context: ../TopicosAvancados-PasseioTuristicoAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/db_passeiosturisticos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  turismo-node:
    build:
      context: ../TopicosAvancados-PasseioTuristicoAPI-Node
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  turismo-react:
    build:
      context: ../TopicosAvancados-PasseioTuristicoAPI-Front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API1_URL=http://turismo-java:8080/api/
      - REACT_APP_API2_URL=http://turismo-node:3001/api2/
    depends_on:
      - turismo-java
      - turismo-node
    command: sh -c "npm start"

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: always
    privileged: true
    user: root
    tty: true
    stdin_open: true
    ports:
      - 8090:8080
      - 50000:50000
    container_name: "jenkins"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
  mysql_data: